Practicing git on EMACAS with magit.
* Useful link
https://www.youtube.com/watch?v=vQO7F2Q9DwA
Magit Introduction and Demonstration, by Howard Abrams, 
shows e-diff, fetch, merge, rebase, squash.

* Discarding uncommitted changes

On the main magit buffer, (C-x g), the Unstaged changes are displayed per file.  Type Meta-N to get to the file that you wish to examine.  Then type Meta-TAB to open up a view of the uncommitted changes.  Then type Meta-N to get to the hunk - i.e. section - of changes that you want to undo.  Then type k to cancel the changes in that section.  Note: Meta-TAB toggles folding-unfolding of subsections.

* View log + Reset to previous node, discarding recent commits

To view a log of commits, press l to switch to log and then l again to show log of current part of the tree. 

To reset the repository to an earlier commit, move to that commit (by pressing meta-n, or by searching forward to some text in the commit), and then press x.  Magit shows in the minibuffer the pointer to the commit that you have chosen, in a form relative to the current location of the HEAD, and lets you confirm the reset.  The work tree (the current contents of the working folder for this repository) is set to the commit which you chose, and all commits after this commit are discarder (lost for ever). 

* Overview of items from magit menu
Concepts to discuss - from the menu items of Magit:

** Popup and dwim commands
*** A - Cherry-picking

*** b Branching

*** B Bisecting

*** c Committing

*** d Diffing

*** D Change diffs

*** e Ediff dwimming

*** E Ediffing

*** f Fetching

*** F Pulling

*** l Logging

*** m Merging

*** M Remoting

*** o Submodules

*** P Pushing

*** r Rebasing

*** t Tagging

*** T Notes

*** V Reverting

*** w Apply patches

*** W Format patches

*** y Show Refs

*** z Stashing

*** | Running


** Applying changes
*** a Apply
*** s Stage
*** u Unstage
*** v Reverse
*** S Stage alll
*** U Unstage all
*** k Discard

** Misc basic

*** g refresh current buffer

*** TAB toggle section at point

*** RET visit thing at point

*** C-h m show all key bindings

** Common Commands

*** C-c C-c Set defaults

*** C-h i View popup manual

*** C-t Toggle this section

*** C-x C-s Save defaults

*** ? Popup help prefix

*** C-g Abort


